### ISSUE TITLE
Simple Icon Inconsistency

### ISSUE THREAD

**Issue by Strangeland102** [Ballista-Line/Link-Game#4]
When you proceed through the "New Game" option the calendar or "Event Selection" screen looks like this: http://puu.sh/huRim/b6b552f273.jpg

However when I click directly on "Event Selection" from the main menu it looks like this: 
http://puu.sh/huRiZ/8ae685b727.jpg

Further if I click "idle" until the next day after clicking "Event Selection" and come to the calendar the screen it looks like this: http://puu.sh/huRki/e657c25770.jpg

**Comment by Strangeland102** [comment]
The 3rd doesn't seem to be a problem more of just the initiation of the event on the right due to it being in the time parameters for it.

What caught my attention was the flower looking icon that seems to be a bug as it doesn't have a name or any roll-over information.

**Comment by JaidenK** [comment]
The "EventSelection" link is not supposed to be clicked (I just have it their for quick access, and will remove it soon).
The reason the icons are changing is, indeed, due to the event meeting time parameters.
The "flower icon" represents events that are unrelated to any specific character. That event itself is the prologue.
The golden dots represent events that will be available in the future, but are not accessible yet.

I'll close the issue once the EventSelection button is gone.
